### ISSUE TITLE
Download individual files one after the other in a directory without having to get the individual URL

### ISSUE THREAD

**Issue by dutta-alankar** [loribonna/onedrivedownloader#1]
Hi! I thought this is the right place to put this. Apologies if this is irrelevant here.
I'm inexperienced in this. I wish to download the files one after another in the following publicly shared directory without having to note down the links to individual files. Can you please suggest a way to do this? 

[https://indianinstituteofscience-my.sharepoint.com/:f:/g/personal/alankardutta_iisc_ac_in/ErcHs_jJ0XdPsZHXCaQlgZEBfbf2K3uTTtDNqeNIFcRDhw?e=CjqFPS](https://indianinstituteofscience-my.sharepoint.com/:f:/g/personal/alankardutta_iisc_ac_in/ErcHs_jJ0XdPsZHXCaQlgZEBfbf2K3uTTtDNqeNIFcRDhw?e=CjqFPS)

The reason is that the directory size is large and there are a lot of files. So, I think the best way is to download individual files one after another (or in a multiprocessing pool) from the shared directory without having to list the links to individual files manually.

**Comment by loribonna** [comment]
Hi @dutta-alankar. For your particular use case for the moment I suggest to load the URLs of the specific files in a list and then iteratively download each one with the `download` function.

Unfortunately `onedrivedownloader` has no way to understand that a given URL is that of a folder and that it should download each one (although it sure seems a neat feature to have, maybe in the future).

**Comment by dutta-alankar** [comment]
Thanks a lot for the idea! I'm currently doing that exactly. I have manually generated all the links of all the files and stored in a separate file from which I'm reading it.
